spring:
  application:
    name: gateway
hackaton:
  cartao:
    api:
      url: http://localhost:8081
  autenticacao:
    api:
      url: http://localhost:8082
  cliente:
    api:
      url: http://localhost:8083
  pagamentos:
    api:
      url: http://localhost:8084

route:
  config:
    routes:
      - path: "/api/cliente"
      - path: "/api/cartao"
      - path: "/api/pagamentos"
        secured: true
server:
  port: 8080
